### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [BomLe/sql-scratch-capstone-turn-in#1]
Overall, your work meets the project requirements -- great work!

I don't really have any issues with your SQL queries -- looks good to me!
As for your presentation, I think it looks really clean but here are some suggestions:
I don't think you should show the simpler SQL queries at all. They're insignificant and only confuse an audience member who may not know about SQL. Make the font bigger so that it is easier to read. If you are only going to have a slide that isn't even going to be half a slide in height, it shouldn't be a slide own its own.

**Comment by BomLe** [comment]
Awesome, thanks very much for the review and the great suggestions, @hmontero1205 !
